<template>
  <section class="support_en">
    <section class="title">
      <h2>CoinU Terms of Service</h2>
      <p>V1.0 2018-7-1</p>
    </section>
    <section class="detail">
      <p>Before you start reading and decide whether to accept the CoinU Privacy Agreement (here referred to as "this
        Agreement") Creditshares specifically reminds you to read carefully the content of this agreement regarding
        restrictions on Creditshares liability and increased your obligations.</p>

      <p>Please read this agreement carefully before you use the website, the application and accept the services we
        provide.</p>

      <p>1. Confirmation and Acceptance of this Agreement</p>
      <p>1.1 You understand that this Agreement and related agreements apply to applications and services developed and
        owned by Creditshares on CoinU and CoinU, including but not limited to decentralized applications ("DApp")
        (excluding DApps developed by third parties), centralized Application (referred to as "App") (excluding DApps
        developed by third parties).</p>
      <p>1.2 After you download CoinU and start to create or import wallet, you are deemed as having read and accepted
        this Agreement, which shall cause this Agreement to become effective and legally binding on both you and
        Creditshares immediately.</p>
      <p>1.3 Creditshares may update this Agreement at any time based on its own judgments on business, legal and policy
        factors. Once the revised agreement is published, it will automatically take effect immediately. If you are
        unable to accept some of the terms of this agreement, you can contact us and stop using CoinU Wallet until you
        have reached an agreement with us. Use of CoinU by you after any modification to this Agreement constitutes your
        acceptance of this Agreement as modified.</p>
      <p>1.4 Before using our services, please confirm that you are at least 18 years of age.</p>

      <p>
        2. Definition
      </p>
      <p>2.1 CoinU: Creditshares (Beijing) Technology Co., Ltd. independently develops, operates, manages, and enjoys
        legal ownership of the software platform/website/mobile app client, providing a blockchain currency asset local
        wallet service with the domain name www.coinu. Top, support for use on Android systems and iOS systems.
        Creditshares provides users with local, online management services for blockchain currency assets.</p>

      <p>2.2 User:</p>
      <ul>
        <li> a User must be a natural person who possesses full capacity for civil acts;</li>
        <li>if you are under 18 years old, please use CoinU under the guidance of your parents or guardians. If any
          person of no capacity for civil acts conducts any transactions on CoinU or any person of limited capacity for
          civil acts conducts any transaction which does not commensurate his/her civil rights or act capacity, the
          parents or guardians of the User shall be liable for the consequences of such transactions.
        </li>
      </ul>
      <p>
        2.3 Blockchain: A chained data structure that combines data blocks in a sequential manner and cryptographically
        ensures a non-tamperable and unforgeable distributed ledger. It uses blockchain data structures to validate and
        store data, uses distributed nodes and consensus algorithms to generate and update data, uses cryptographic
        methods to secure data transfers and access, and uses intelligent contracts composed of automated script code to
        program and Operational data is a new form of distributed infrastructure and computing paradigm.
      </p>
      <p>2.4 Blockchain asset or blockchain currency asset: A number in a cryptographic account that exists in the
        blockchain data. It is considered a currency asset to the legal owner of the account, including but not limited
        to BTC (bitcoin),ETH（Ethereum)etc.</p>
      <p>2.5 HD wallet: Hierarchical Deterministic wallet (HD Wallet), a software tool for storing blockchain assets.
        The key of the HD wallet is controlled by the user, not the other party outside the user. CoinU is For local HD
        wallets, users are responsible for the control and security of the blockchain assets. Creditshares does not
        assume the custody obligations or other related responsibilities of the user's HD wallet assets.
      </p>
      <p>
        2.6 Mnemonic: Complies with the blockchain BIP39 industry standard, consisting of 12 ordered words generated by
        a random algorithm. It is an easy-to-record expression of the private key, which is convenient for users to
        backup and keep. The process of creating a mnemonic belongs to the local behavior of the user. It can be
        operated in the case of disconnected network, and has nothing to do with the server. Therefore, the CoinU wallet
        does not grasp the user mnemonic, and cannot manage the wallet assets of the user, nor can it find the user.
        Return to the words. CoinU wallets follow the
        <strong>BIP32, BIP39, and BIP44</strong> standards, and any other wallet that complies with this standard can
        use the same mnemonic to recover and manage your blockchain assets.
      </p>
      <p>2.7 Wallet password: A six-digit number used to unlock a mobile device with a CoinU wallet. It helps protect
        your assets from being stolen. If you forget your wallet password, you can use the mnemonic words to recover
        your wallet. Digital assets will Not be affected.</p>
      <p>2.8 Transaction fee: The transaction confirmation fee paid to the blockchain miner node when the user transfers
        the assets on the blockchain. The fee collector is the miner, and Creditshares will not charge you any fees.</p>
      <p>3. Services</p>
      <p>3.1 Create or import a wallet: For blockchain currency assets supported by CoinU, you can use CoinU to generate
        a new wallet or import a previously generated wallet via the mnemonic words.</p>
      <p>
        3.2 Transfer and receive Tokens: You can use CoinU's transfer and collection functions to manage currency
        assets, that is, use the private key for electronic signature, and modify the ledger of the relevant blockchain.
        Transfer means that the payer uses the blockchain address of the payee to perform the transfer operation, and
        the actual transfer and collection behaviors occur in the relevant blockchain system.
      </p>
      <p>3.3 Transaction records: We will copy all or part of your transaction history through the blockchain system.
        The transaction records are based on the records of the corresponding blockchain system.</p>
      <p>3.4 Manage Tokens: You can use CoinU to add and maintain currency assets supported by CoinU.</p>
      <p>3.5 New message notification: CoinU will send you a notice by means of website announcement, new message
        notification, pop-up reminder or client notification, such as notifying you of the transaction result, or
        prompting you to perform related operations, please pay attention to it.</p>
      <p>3.6 Other services that Creditshares would like to provide.</p>
      <p>4. Privacy Policy
      </p>
      <p> 4.1 Your privacy is of utmost importance for Creditshares. Please refer to CoinU Privacy Policy as updated by
        us from time to time for relevant privacy protection policies < CoinU Privacy Policy >.
      </p>
      <p>5. Risks</p>
      <p>5.1 You understand and acknowledge that the blockchain technology is a field of innovation where the laws and
        regulations are not fully established. You also understand that Tokens have much higher volatility comparing to
        other financial assets. You shall make investment decisions and hold or dispose of the Tokens in a reasonable
        way and corresponding to your financial status and risk preferences.</p>
      <p>5.2 If you or your counterparty fails to comply with this Agreement or fails to follow the instructions, tips
        or rules on the website or on the page of the transaction or payment, CoinU does not guarantee successful
        transfer of the Tokens and CoinU shall not be held liable for any of the consequences of such failure. If you or
        your counterparty has already received the payment in CoinU wallet or third-party wallet, you understand that
        transactions on blockchain are irreversible and irrevocable. You and your counterparty shall assume the
        liabilities and consequences of your transactions.</p>
      <p>5.3 It is your sole responsibility to make sure that your counterparty is a person with full capacity for civil
        acts and decide whether you shall transact with him/her.</p>
      <p>5.4 You shall check the official blockchain system or other blockchain tools when you receive Alert such as
        “transaction failed” or “mining overtime” in order to avoid repetitive transfer. If you fail to follow this
        instruction, you shall bear the losses and expenses occurred due to such repetitive transfer. You understand
        that the following reasons may result in “transfer failed” or “mining overtime”:</p>
      <ul>
        <li>insufficient balance in wallet;</li>
        <li>insufficient gas for transaction;</li>
        <li>blockchain’s failure to execute the code of smart contracts;</li>
        <li>technical failure of the network or equipment;</li>
        <li>abandoned transactions result from blockchain network congestion or failure.</li>
      </ul>

      <p>

        5.5 You understand that after you create or import wallet on CoinU, your Keystore, Private Key and Mnemonic
        Words are only stored on your mobile device and will not be stored in CoinU or on the servers of Creditshares.
        You may change another mobile device to use CoinU after you follow the instructions on CoinU to backup your
        wallet. If you lose your mobile device before you could write down or backup your Wallet Password, Private Key,
        Mnemonic Words or Keystore, you may lose your Tokens and Creditshares is unable to restore them. If your Wallet
        Password, Private Key, Mnemonic Words or Keystore is disclosed or the device which stores or holds your Wallet
        Password, Private Key, Mnemonic Words or Keystore is hacked or attacked, you may lose your Tokens and
        Creditshares is unable to restore them. You shall bear the foregoing losses on your own.
      </p>
      <p>5.6 We suggest you backup your Wallet Password, Private Key, Mnemonic Words and Keystore when you create or
        import wallet by writing them down on papers or backup them in password management apps. Please do not use
        electronic methods such as screenshots, e-mails, note-taking apps in cell phones, text messages, WeChat or QQ to
        backup any of the above information.</p>
      <p>5.7 In order to avoid potential security risks, we suggest you use CoinU in a secured network environment.
        Please do not use a jailbreak or Rooted mobile device.</p>
      <p>5.8 Please be alert to frauds when you use CoinU. If you find any suspicious conducts, we encourage you to
        inform us immediately.</p>
      <p>6. Change, Suspension, Termination of Creditshares Service</p>
      <p>6.1 You acknowledge and accept that Creditshares may, at its sole discretion, provide only a part of services
        for the time being, suspend certain services or provide new services in the future. When we change our services,
        your continuous use of CoinU is deemed as your acceptance of this Agreement and revisions of this Agreement.</p>
      <p>6.2 After the new version of the software is released, the old version may not be available. Creditshares does
        not guarantee the security, continued usability and service of the old version. Please check and install the
        latest version at any time.</p>
      <p>You understand that Creditshares may suspend services under the following circumstances:</p>

      <ul>
        <li>due to the maintenance, upgrading, failure of equipment and blockchain system and the interruption of
          communications etc., which lead to the suspension of the operation of CoinU;
        </li>
        <li>due to force majeure events including but not limited to typhoon, earthquake, tsunami, flood, power outage,
          war, or terrorist attacks, or computer viruses, Trojan Horse, hacker attacks, system instability or government
          behaviors and other reasons, Creditshares is unable to provide services or in Creditshares’ reasonable
          opinion, continuous provision of services would result in significant risks;
        </li>
        <li>due to other events which Creditshares cannot control or reasonably predicate.</li>
      </ul>

      <p>
        6.4 Creditshares reserves the right to unilaterally suspend or terminate all or part of the function of CoinU
        under the following circumstances:
      <ul>
        <li>death of Users;</li>
        <li>if you steal others’ wallets information or mobile devices;</li>
        <li>if you provide false Personal Information on CoinU;</li>
        <li>if you refuse to allow mandatory update of CoinU;</li>
        <li>if you use CoinU to commit illegal or criminal activities;</li>
        <li>if you hinder the normal use of CoinU by other Users;</li>
        <li>if you pretend to be staff or management personnel of Creditshares;</li>
        <li>if you threaten the normal operation of Creditshares computer system by attack, invasion, alternation or any
          other means;
        </li>
        <li>if you use CoinU to send spams;</li>
        <li>if you spread rumors which endanger the goodwill of Creditshares and CoinU;</li>
        <li>if you conduct any illegal activities, breach this Agreement etc. or other circumstances under which
          Creditshares reasonably considers necessary to suspend services.
        </li>
      </ul>
      <p>6.5 You are entitled to export your wallets within a reasonable amount of time if Creditshares changes,
        suspends or terminates its services.</p>
      <p>7. Your Representations and Warranties</p>
      <p>7.1 You shall comply with: 1) all applicable laws and regulations of PRC and 2) all applicable laws and
        regulations of the country or area you reside in. You shall not use CoinU for any unlawful purposes or by any
        unlawful means.</p>
      <p>7.2 You shall not use CoinU to commit any illegal or unlawful activities, including but not limited to:</p>


      <ul>
        <li>activities opposing the basic principles set forth in the PRC’s Constitution, endangering national security,
          disclosing state secrets, overturning the government or undermining national unity;
        </li>
        <li> any illegal conducts, such as money laundering, illegal fund raising etc.;</li>
        <li> accessing Creditshares services, collecting or processing the content provided by Creditshares, intervening
          or attempting to intervene any Users, by the employment of any automated programs, software, network engines,
          web crawlers, web analytics tools, data mining tools or similar tools etc.;
        </li>
        <li>providing gambling information or inducing others to engage in gambling;</li>
        <li>invading into others’ CoinU wallets to steal Tokens;</li>
        <li>engaging in any inaccurate or false transactions with the counterparty;</li>
        <li>committing any activities which harms or attempts to harm CoinU service system and data;</li>
        <li>other activities which Creditshares has reason to believe are inappropriate.</li>
      </ul>
      <p>7.3 You understand and accept that you shall be responsible for any violation of law (including but not limited
        to the regulations of the Customs and Tax) or for breach of this Agreement by you and shall indemnify
        Creditshares against the losses, the third-party claims or administrative penalties against Creditshares
        incurred by such violation or breach, including reasonable attorney’s fees.
      </p>
      <p>7.4 You confirm that you will pay the service fees charged by Creditshares in time (if applicable).
        Creditshares reserves the right to suspend the services when the User fails to pay service fees (if applicable).
      </p>
      <p>8. Disclaimer and Limitation of Liability</p>
      <p>8.1 Creditshares only undertakes obligations expressly set forth in this Agreement.
      </p>
      <p>8.2 YOU ACKNOWLEDGE AND ACCEPT THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE PRC LAW, COINU IS PROVIDED
        ON AN “AS IS”, “AS AVAILABLE” AND “WITH ALL FAULTS” BASIS. Creditshares shall not be held liable for malfunction
        of CoinU which results from the following reasons:
      </p>

      <ul>
        <li>system maintenance or upgrading of CoinU;
        </li>
        <li>force majeure, such as typhoon, earthquake, flood, lightning or terrorist attack etc.;</li>
        <li>malfunction of your mobile device hardware and software, and failure of telecommunication lines and power
          supply lines;
        </li>
        <li>your improper, unauthorized or unrecognized use of Creditshares services;</li>
        <li>computer viruses, Trojan Horse, malicious program attacks, network congestion, system instability, system or
          equipment failure, telecommunication failure, power failure, banking issues, government acts etc.;
        </li>
        <li>any other reasons not imputed to Creditshares.</li>
      </ul>


      <p>8.3 Creditshares shall not be held liable under the following circumstances:</p>

      <ul>
        <li>Users lose their mobile devices, delete CoinU applications and wallets without back-up, forget Wallet
          Passwords, Private Keys, Mnemonic Words, Keystores without back-up, which result in the loss of their Tokens;
        </li>
        <li>Users disclose their Wallet Passwords, Private Keys, Mnemonic Words, Keystores, or lend or transfer their
          CoinU wallets to others, or authorize others to use their mobile devices or CoinU wallets, or download CoinU
          applications through unofficial channels, or use CoinU applications by other insecure means, which result in
          the loss of their Tokens;
        </li>
        <li>Users mishandle CoinU (including but not limited to wrong address, failure of the node servers selected by
          you), which result in the loss of Tokens;
        </li>
        <li>Users are unfamiliar with the knowledge of blockchain and their mishandling of CoinU results in loss of
          their Tokens;
        </li>
        <li> CoinU is unable to copy accurate transaction records due to system delay or blockchain instability etc.;
        </li>
        <li>Users shall undertake the risks and consequences of their transactions on the third-party-developed DApps.
        </li>
      </ul>
      <p>8.4 You understand that CoinU is only an management tool for Tokens which is incapable to control the quality,
        security and legitimacy of products and services provided by the third-party-developed DApps, or the
        authenticity and accuracy of their information and their capabilities to fulfill the obligations under the
        agreements with you. You, at your sole discretion, decide whether to transact on the third-party-developed
        DApps. It is the third-party-developed DApps, instead of CoinU, that transact with you. We kindly remind you to
        carefully review the authenticity, legitimacy, and effectiveness of related information provided by the
        third-party-developed DApps before you decide to use the DApps. In addition, you shall also assume all the risks
        arising from the transactions between you and any third party exchanges.</p>
      <p>8.5 You acknowledge that CoinU may provide services to you and your counterparties simultaneously and you agree
        to waive any actual or potential conflicts of interests and will not claim against Creditshares on such base or
        burden Creditshares with more responsibilities or duty of care.</p>
      <p>8.6 Creditshares does not warrant that:</p>

      <ul>
        <li>services provided by Creditshares would satisfy all your needs;
        </li>
        <li>all techniques, products, services, information or other materials from Creditshares would meet your
          expectations;
        </li>
        <li>all the transaction information in currency tokens markets captured from the third party exchanges are
          prompt, accurate, complete, and reliable;
        </li>
        <li>your counterparties on CoinU will perform their obligations in the transaction agreements with you timely.
        </li>
      </ul>
      <p>8.7 You are aware that CoinU is only a tool for Users to manage their Tokens and to display transaction
        information. Creditshares does not provide legal, tax or investment advice. You shall seek advice from
        professional legal, tax, and investment advisors. In addition, Creditshares shall not be liable for any
        investment loss, data loss etc. during your use of our service.</p>
      <p>8.8 You understand that we may change our entry standards, limit the range and ways to provide services for
        specific Users etc. at any time in accordance with PRC laws and regulations.</p>
      <p>9. Intellectual Property Rights Protection</p>

      <p>9.1 CoinU is an application developed and owned by Creditshares. The intellectual property rights of any
        contents displayed in CoinU (including this Agreement, announcements, articles, videos, audios, images,
        archives, information, materials, trademarks or logos) are owned by Creditshares or the third party licensors.
        Users can only use the CoinU applications and its contents for the purpose of holding and managing their Tokens.
        In particular, without prior written consent from CoinU or the third party licensors, no one shall use, modify,
        decompile, reproduce, publicly disseminate, alter, distribute, issue or publicly publish the abovementioned
        applications and contents.
      </p>
      <p>10. Term of agreement
      </p>
      <p>10.1 The agreement you and us have established is a non-fixed term agreement, and we have the right to
        terminate the contract at any time and take effect immediately if you:</p>
      <ul>
        <li>You violate or violate any of the terms of this Agreement;</li>
        <li>We believe that you are abusing an application or service.
        </li>
      </ul>
      <p>11. Governing Law and Dispute Resolution</p>
      <p>11.1 If any dispute or claim in connection with this Agreement arises between you and Creditshares, the parties
        shall first attempt to resolve the dispute or claim through amicable negotiations in good faith. If the parties
        cannot reach an agreement, either party may sue the other party at the competent court where Creditshares is
        located.</p>
      <p>12. Miscellaneous</p>
      <p>12.1 If you live outside of PRC, you shall fully understand and conform to the laws, regulations and rules in
        your jurisdictions which are relevant to use of Creditshares services.</p>
      <p>12.2 During your use of Creditshares services, if you come across any problems, you can contact us through the
        submission of your feedbacks on CoinU.</p>
      <p>12.3 This Agreement is accessible for all Users on CoinU. We encourage you to read this Agreement each time you
        log onto CoinU.</p>
      <p>12.4 Any translations of this Agreement are provided for convenience only and are not intended to be modified
        by the terms of this policy. If there is a conflict between the Chinese version and the non-Chinese version of
        this policy, the Chinese version shall prevail.
      </p>

      <p>As for any issues not covered in this Agreement, you shall comply with the announcements and relevant rules as
        updated by Creditshares from time to time.</p>
      <p>The final interpretation of this agreement is owned by Creditshares.</p>
      <p>The agreement begins to be applicable since July 1, 2018.</p>
    </section>
  </section>
</template>

<script>
  export default {
    name: "supportEn"
  }
</script>

<style lang="stylus">

</style>
